# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os:
  - linux
  - osx
  - windows

r_check_args:

# Tell Travis that we're using bioconductor packages.
# Could also use bioc-release  
r: bioc-devel
# warnings_are_errors: false

# Tell Travis to run BiocCheck.
bioc_check: true

# Install the covr dependancy
r_packages:
  - covr

# Run the coverage tests after a successful build.  
after_success:
  - Rscript -e 'covr::codecov(type="all")'      